apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: xxx
  labels:
    app: project_name
  name: project_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project_name
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: project_name
    spec:
      containers:
      - image: xxx
        imagePullPolicy: Always
        name: project_name
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: VAULT_ROLE_ID
            value: vault_role_id
          - name: VAULT_SECRET_ID
            value: vault_secret_id
          - name: VAULT_NAMESPACE
            value: vault_namespace
        resources:
           requests:
             memory: "100Mi"
             cpu: "400m"
           limits:
              memory: "200Mi"
              cpu: "800m"